# /git_lab/git_lab_prod/projects/git_env/bin/ansible-playbook build.yml -vvvv
---
  - name: Deploy an OKE Kubernetes Cluster
    hosts: 127.0.0.1
    environment:
      PYTHONPATH: '/git_lab/git_lab_prod/projects/ansible_modules/OCIC'
      OCI_TENANCY: 'ocid1.tenancy.oc1..aaaaaaaaf6jvsq24uaib65js2zpdq6tqdsjn7ru65d7oui6wz6j7epivk4sa'
      OCI_USER_KEY_FILE: '/home/oracle/.oci/oci_api_key.pem'
      OCI_USER_FINGERPRINT: '9a:ef:fb:dc:31:9e:76:d9:66:0f:dc:c6:fc:57:98:05'
      OCI_USER_ID: 'ocid1.user.oc1..aaaaaaaazfyqk3drcmctldmaqh63dqlwtd65vgvmv3ziue7g6otskwwkxkra'
      HTTP_PROXY: 'http://ges-proxy.oracle.com:80'
      HTTPS_PROXY: 'http://ges-proxy.oracle.com:80'
    vars:
      course_title: '<gcc_name>'
      tenancy_id: 'ocid1.tenancy.oc1..aaaaaaaaf6jvsq24uaib65js2zpdq6tqdsjn7ru65d7oui6wz6j7epivk4sa'
      idcs_name: 'idcs-9e3216aa4f3c441c81d1a0e44dd651c1'
      admin_account_username: 'gitousupport'
      admin_account_password: 'WAzJHBnfnX6*'
      domain_id: 'ouocictrng17'
      psm_endpoint: 'psm.us.oraclecloud.com'
      devcs_name: 'AutoDevCs'
      event_id: '1607999'
      student_user: 'ora003'
      oci_user: 'lab.user03'
      oci_step: 'true'
      client_id: '96a390a0896243e18e80c812144e5724'
      client_secret: 'e19c1774-e045-4d93-8218-b298501626fe'
      log_path: '/tmp/1607999'
      oci_region: 'us-ashburn-1'
      role_list:
          - 'DEVELOPER_ADMINISTRATOR'
          - 'DEVELOPER_USER'




    roles :
      - deploy_kuber_build


  - name: Create a OCI connection
    hosts: selenium_compute
    vars:
      tenancy_id: 'ocid1.tenancy.oc1..aaaaaaaaf6jvsq24uaib65js2zpdq6tqdsjn7ru65d7oui6wz6j7epivk4sa'
      domain_id: 'ouocictrng17'
      log_path: '/tmp/1607999'
      admin_account_username: 'gitousupport'
      admin_account_password: 'WAzJHBnfnX6*'


    roles :
      - oci_connection



