---

  - name: Delete the pem file
    file:
      path: '/home/opc/keys/oci_api_key.pem'
      state: absent



  - name: copy the pem file to selenium server
    copy:
      src: '{{ log_path }}/oci_api_key.pem'
      dest: '/home/opc/keys/oci_api_key.pem'


  - name: Kill all firefox process
    shell: pkill -f /opt/firefox59/firefox-bin
    args:
      chdir: /home/opc
    ignore_errors: yes


  - name: Kill all geckodriver process
    shell: pkill -f /usr/bin/geckodriver
    args:
      chdir: /home/opc
    ignore_errors: yes


  - name: Create OCI connection through selenium script
    shell: 'MOZ_HEADLESS=1 python3 dev_selenium.py {{hostvars["127.0.0.1"]["dev_url"] |regex_replace(":443", "")}}  {{tenancy_id}} {{hostvars["127.0.0.1"]["user_id"]}} {{hostvars["127.0.0.1"]["dev_comp_id"]}} {{ domain_id }} {{admin_account_username}} "{{admin_account_password}}" /home/opc/keys/oci_api_key.pem {{hostvars["127.0.0.1"]["fingerprint"]}}'
    args:
      chdir: /home/opc

