---
- hosts: all
  become: true
  vars_files:
    - vars.yml
  vars:
    download_folder: /tmp
    java_src: jdk-11.0.11_linux-x64_bin.rpm
    java_name: "jdk-11.0.11"
  tasks:

    - name: Update repos.
      yum:
        name: "*"
        state: latest
        update_cache: true

    - name: Create user Oracle.
      user:
        name: oracle
        createhome: true
        password: "{{ vaulted_password | password_hash('sha512') }}"
        group: oracle

    - name: Set authorized key from file.
      authorized_key:
        user: oracle
        state: present
        key: "{{ lookup('file', '{{ ssh_home }}/ansible.pub') }}"

    - name: add Oracle to sudoers file.
      lineinfile:
        path: /etc/sudoers
        line: "oracle  ALL=(ALL) NOPASSWD:ALL"

    - name: Remove openJDK if it's there.
      yum:
        name: open-jdk
        state: absent

    - name: Copy Java JDK rpm file to server.
      copy:
        src: "{{ download_file_src }}/{{ java_src }}"
        dest: "{{ download_folder }}"
        mode: 0644

    - name: Install the rpm file.
      yum:
        name: "{{ download_folder }}/{{ java_src }}"
        state: present

    - name: Fix ownership.
      file:
        path: "/{{ java_name }}"
        owner: root
        group: root
        recurse: true
        state: directory

    - name: Make Java available for system.
      command: >
        alternatives --install "/usr/bin/java"
        "java" "/{{ java_name }}/bin/java" 2000
      changed_when: false

    - name: Clean up files.
      file:
        path: "{{ download_folder }}/{{ java_name }}"
        state: absent
