---
- hosts: localhost
  gather_facts: false
# this is a 'play' include
- import_playbook: listofplays.yml

- name: another play
  hosts: all
  tasks:
    - debug: 
        msg: "*** main_import "

# this is a 'task' include
#   - import_playbook: stuff.yml