# /git_lab/git_lab_prod/projects/git_env/bin/ansible-playbook build.yml -vvvv
---

  - name: Create an DevOps Fund Environment
    hosts: 127.0.0.1
    environment:
      PYTHONPATH: '/git_lab/git_lab_prod/projects/ansible_modules/OCIC'
      OCI_TENANCY: 'ocid1.tenancy.oc1..aaaaaaaaku2h6rz36p2xqbh2lugpa7cuunc74uzi6bu7keead226yfakmbfa'
      OCI_USER_KEY_FILE: '/home/oracle/.oci/oci_api_key.pem'
      OCI_USER_FINGERPRINT: '9a:ef:fb:dc:31:9e:76:d9:66:0f:dc:c6:fc:57:98:05'
      OCI_USER_ID: 'ocid1.user.oc1..aaaaaaaaps5lmmwx62a4xuymrfkqmrnby6sraythubzjdzwttnl7ykqzp4ka'
      HTTP_PROXY: 'http://ges-proxy.oracle.com:80'
      HTTPS_PROXY: 'http://ges-proxy.oracle.com:80'
    vars:
      course_title: '<gcc_name>'
      tenancy_id: 'ocid1.tenancy.oc1..aaaaaaaaku2h6rz36p2xqbh2lugpa7cuunc74uzi6bu7keead226yfakmbfa'
      idcs_name: 'idcs-73c8979b529e4449b5e5b854889874bc'
      admin_account_username: 'gitousupport'
      admin_account_password: 'WAzJHBnfnX6*'
      client_id: '7dd24e113bf444eeac5dbd77608a9309'
      client_secret: 'ad1b1e4c-0511-4ee0-9995-d8c29087ff2a'
      jcs_endpoint: 'jaas.oraclecloud.com'
      devcs_name: 'AutoDevCS'
      dbcs_name: 'Devdb'
      jcs_name: 'DevCsJCS'
      domain_id: 'ocuocictrng14'
      event_id: '11223344'
      log_path: '/tmp/11223344'
      admin_wls_user: 'weblogic'
      admin_wls_password: 'Welcome_1234'
      db_password: 'Welcome_#1234'
      oci_region: 'uscom-east-1'
      student_user: 'ora001'
      oci_user: 'lab.user01'
      oci_step: 'true'
      role_list:
          - 'DEVELOPER_ADMINISTRATOR'
          - 'DEVELOPER_USER'


    roles :
      - agile_dev_build


  - name: Create a OCI connection
    hosts: selenium_compute
    vars:
      tenancy_id: 'ocid1.tenancy.oc1..aaaaaaaaku2h6rz36p2xqbh2lugpa7cuunc74uzi6bu7keead226yfakmbfa'
      user_ocid: 'ocid1.user.oc1..aaaaaaaaps5lmmwx62a4xuymrfkqmrnby6sraythubzjdzwttnl7ykqzp4ka'
      domain_id: 'ocuocictrng14'
      log_path: '/tmp/11223344'
      admin_account_username: 'gitousupport'
      admin_account_password: 'WAzJHBnfnX6*'


    roles :
      - oci_connection


