---
      - name: Reload Squid service
        service:
          name: '{{ item }}'
          state: 'reloaded'
        with_items:
          - 'squid'
        become: yes


      - name: Start Squid service
        service:
          name: '{{ item }}'
          state: 'started'
        with_items:
          - 'squid'
        become: yes
