---
- name : List summary of existing buckets in OCI object storage
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  vars_files: vars.yml
  tasks:
    - name: List bucket facts
      oci_object_storage_bucket_facts:
         namespace_name: "{{ namespace_name }}"
         compartment_id: "{{ compartment_id }}"
      register: result
    - name: Dump result
      debug: 
        msg: '{{result}}'