---
- name : List summary of existing buckets in OCI object storage
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
    - name: List bucket facts
      oci_object_storage_bucket_facts:
         namespace_name: 'ocuocictrng14'
         compartment_id: 'ocid1.compartment.oc1..aaaaaaaanja7fndva7wuyc4ng57lzbfzevqwaas3rzlkepxw3rifrjnssxma'
      register: result
    - name: Dump result
      debug: 
        msg: '{{result}}'