---
- hosts: all
  become: true
  vars_files: vars/main_vars.yml

  tasks:

    - name: import yum update.
      import_tasks: update_yum.yml

    
    # - name: import create user.
    #   import_tasks: create_user.yml

# appedn if not exist, replace if it does
# all following  tasks have access to these env vars
# use copy of tempaltesif you have a lot of env vars
    - name: Add an environment variable to the remote user's shell.
      lineinfile:
        dest: ~/.bash_profile
        regexp: '^JAVA_HOME='
#        line: "JAVA_HOME=/usr/java/jdk_11.0.11"
        line: "JAVA_HOME={{ java_home }}"
      tags: user        

    - name: Get the value of the environment variable we just added.
      shell: 'source ~/.bash_profile && echo $JAVA_HOME'
      register: foo
    - name: Print the value of the environment variable.
      debug:
        msg: "The variable is {{ foo.stdout }}"
      tags: users        


    - name: Get list of groups.
      command: groups
      register: group_list
      changed_when: false
      tags: user      

    - name: Print groups.
      debug:
        msg: "The groups are: {{ group_list }}"
      tags: user        
# use stdout to just get the groups

    - name: Install Apache.
      yum:
        name:
          - httpd
          - httpd-devel
        state: absent
      register: apache_stat

    - name: print apache stat.
      debug:
        msg: "Apache status: {{ apache_stat.results[0] }}"

    - name: Make sure Apache is started now and at boot.
      service:
        name: httpd
        state: started
        enabled: true
      notify:
        - Restart Apache
      when: apache_stat.results[0] != "httpd is not installed"

    - name: Open port 80 for http access
      firewalld:
        service: http
        permanent: true
        state: enabled
      notify:
        - Restart firewalld
# handlers only fire on change
# handlers can call other handlers
# force handlers to fire with meta: flush_handlers
# --force-handlers at command line - so they run even on fail
  handlers:
    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted

    - name: Restart Apache
      service:
        name: httpd
        state: restarted