---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: First task.
      debug:
        msg: task1

- name: Import this is playbook.
  import_playbook: listofplays.yml

- name: Import another Playbook.
  import_playbook: more_plays.yml

- hosts: localhost
  tasks:
    - name: First task after first play.
      debug:
        msg: Play 2 task 1

