---
# Sample file to test Ansible on OCI
- collections:
    - oracle.oci
- hosts: javaoci-oel8
  vars_files: vars/main_vars.yml
  tasks:
    - name: Get compartment id.
      oci_compartment_facts:
        compartment_id: '{{ tenancy_id }}'
        name: "{{ compartment_name }}"
      register: return_object

    - name: print compartment id info.
      debug:
        var: return_object

- include: compute_create.yml compartment_id={{return_object.compartments[0].id}}
- include: create_readme.yml