# /git_lab/git_lab_prod/projects/git_env/bin/ansible-playbook build.yml -vvvv
---
 # - name: Create OCI Compute Instance. 
- hosts: javaoci-oel8
  vars-files: vars/main_vars.yml

      
  roles:
    - inst_create


- name: Restart the squid server
  hosts: proxy_server
  gather_facts: no


  roles:
    - restart_proxy


- name: Execute Post build scripting to perform several post install tasks inside the oci compute instance
  hosts: compute_instance
  gather_facts: no

  vars:
    event_id: '20210517'
    student_user: 'ora001'
    compute_instance_name_prefix: '<compute_instance_name_prefix>'
    instance_name: "{{compute_instance_name_prefix}}{{student_user | regex_replace('-', '')}}"
    pwd_oracle: 'OU{{ event_id }}'
    pwd_root: 'OU{{ event_id | int + 100 }}'

  roles:
    - postinstall


- name: Concatenating the README file
  hosts: 127.0.0.1
  environment:
    PYTHONPATH: '/git_lab/git_lab_prod/projects/ansible_modules/OCIC'
    OCI_USER_KEY_FILE: '/home/oracle/.oci/oci_api_key.pem'
    OCI_USER_FINGERPRINT: '9a:ef:fb:dc:31:9e:76:d9:66:0f:dc:c6:fc:57:98:05'
    OCI_TENANCY: 'ocid1.tenancy.oc1..aaaaaaaaku2h6rz36p2xqbh2lugpa7cuunc74uzi6bu7keead226yfakmbfa'
    OCI_USER_ID: 'ocid1.user.oc1..aaaaaaaaps5lmmwx62a4xuymrfkqmrnby6sraythubzjdzwttnl7ykqzp4ka'
    HTTP_PROXY: 'http://ges-proxy.oracle.com:80'
    HTTPS_PROXY: 'http://ges-proxy.oracle.com:80'
  vars:
    log_path: '/tmp/20210517'
    student_user: 'ora001'

  roles :
    - create_readme

