---
    working_dir: "/home/{{ user }}"
    src_file_dir: "~/Downloads"

    dest_dir: "/home/{{ create_user }}/Downloads/"

    java_src_dir: "{{ src_file_dir }}"
    java_src_file: jdk-11.0.11_linux-x64_bin.rpm

    intellij_src_file: ideaIU-2021.1.1.tar.gz
    intellij_src_dir: "{{ src_file_dir }}"

    jmeter_src_file: 