---

  - name: 'Get information of all service gateways'
    oci_service_gateway_facts:
      compartment_id: '{{ tenancy_id }}'
      region: '{{ oci_region }}'
      vcn_id: '{{ vcn_id }}'
    register: return_object_service_gateway


  - name: 'Deleting service gateways'
    oci_service_gateway:
      id: '{{ item.id }}'
      region: '{{ oci_region }}'
      state: absent
    with_items: '{{ return_object_service_gateway.service_gateways }}'
    loop_control:
      label: "{{ item.display_name }}"
    ignore_errors: yes
