---
  - name: '[{{ oci_region }} : {{ compartment.name }}] Get information of all the load balancers'
    oci_loadbalancer_load_balancer_facts:
      compartment_id: '{{ tenancy_id }}'
      region: '{{ oci_region }}'
    register: return_object_lb
    tags: list


  - name: Delete an load balancer instance
    oci_loadbalancer_load_balancer:
      load_balancer_id: '{{ item.id }}'
      state: 'absent'
      region: '{{ oci_region }}'
      wait: True 
    with_items: '{{ return_object_lb.load_balancers }}'
    loop_control:
      label: '{{ item.display_name }}'
