---

  - name: 'Get information of all Security lists'
    oci_network_security_list_facts:
      compartment_id: '{{ tenancy_id }}'
      region: '{{ oci_region }}'
      vcn_id: '{{ vcn_id }}'
    register: return_object_security_list


  - name: ' Delete security lists'
    oci_network_security_list:
      id: '{{ item.id }}'
      region: '{{ oci_region }}'
      state: absent
    with_items: '{{ return_object_security_list.security_lists }}'
    loop_control:
      label: "{{ item.display_name }}"
    ignore_errors: yes
