---
- name: Install the 'Gnome desktop' environment group.
  yum:
    name:
 #     - "@Workstation"
       - "@GNOME"
       - "@Legacy X Window System Compatibility"
      # - "@GNOME Applications"
#      - "@Server with GUI"
        # - "@development-tools"
        # - "@^gnome-desktop-environment"
 #   state: latest
- 
- name: Change default target to graphical.target.
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link

- name: start the gnome service.
  systemd:
    name: "graphical.target"
    state: started
  notify: restart server
