# _*_ mode: ruby _*_
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
# General Vagrant VM configurations

config.ssh.insert_key = false
config.vm.provider :virtualbox do |v|
v.memory = 4096
#v.linked_clone = true
end

# Control server.
config.vm.define "devops-control" do |ctl|
ctl.vm.hostname = "devops.example.com"
ctl.vm.box = "peru/ubuntu-20.04-desktop-amd64"
ctl.vm.network :public_network, ip:"192.168.0.36"
# ctl.vm.provision :ansible do |ansible|
#     ansible.playbook = "provision.yml"
#   end
#https://www.answertopia.com/ubuntu/ubuntu-remote-desktop-access-with-vnc/
end

#Application server 1.
# config.vm.define "ctl-test" do |ctl2|
# ctl2.vm.box = "peru/ubuntu-20.04-desktop-amd64"
# ctl2.vm.hostname = "ctl-test.example.com"
# ctl2.vm.network :public_network, ip:"192.168.0.201"
#end


#DB server 2.
# config.vm.define "db" do |db|
# db.vm.box = "generic/oracle7"
# db.vm.hostname = "db.example.com"
# db.vm.network :private_network, ip:"192.168.60.12"
# end



end

