---
galaxy_info:
  author: Jakub Gorczyca
  role_name: vnc_server
  description: Ansible role for setting up a VNC server on CentOS 7

  issue_tracker_url: https://github.com/shellbro/ansible-role-vnc-server/issues

  license: BSD

  min_ansible_version: 2.4

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags: []

dependencies: []
